'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {readApiResponse} from '@/lib/api-response';
import {detectPlatform,platformNames,type Platform} from '@/lib/platform';
import type {SocialSnapshot} from '@/lib/social';
import {postPerformance} from '@/lib/performance';
import SessionManager from './session-manager';
import PerformancePanel,{PerformanceOverview,downloadCsv,type Sample} from './performance-panel';
import {Icon,Brand,Modal,PlatformBadge} from './ui';

type Analysis={title?:string;summary?:string;snapshot?:SocialSnapshot;recommendations?:string[]};
type Log={id:string;http_status:number;checked_at:string;ai_analysis_result:Analysis};
type Link={id:string;name:string;url:string;health:string;check_frequency:string;last_checked_at:string|null;link_logs?:Log[]};
type View='overview'|'content'|'accounts'|'ideas';
const health:Record<string,string>={pending:'Sin lectura',healthy:'Disponible',alert:'Lectura parcial',error:'Requiere atención'};
const format=(n:number|null|undefined)=>n===null||n===undefined?'—':n.toLocaleString('es-PY',{maximumFractionDigits:1});
const date=(v:string|null)=>v?new Date(v).toLocaleString('es-PY',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'Aún sin lectura';
const views={overview:{title:'Una mirada. Mejores decisiones.',subtitle:'Tu contenido, tus resultados y el próximo paso.'},content:{title:'Encuentra lo que conecta.',subtitle:'Compara publicaciones y descubre qué despierta interés.'},accounts:{title:'Todo tu universo digital.',subtitle:'Tus cuentas y enlaces, en un solo lugar.'},ideas:{title:'Convierte datos en ideas.',subtitle:'Recomendaciones basadas en las lecturas de tus cuentas.'}};

export default function Dashboard({signedIn}:{signedIn:boolean}){
 const [authenticated,setAuthenticated]=useState(signedIn),[links,setLinks]=useState<Link[]>([]),[loading,setLoading]=useState(true),[view,setView]=useState<View>('overview'),[network,setNetwork]=useState('all'),[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[showSessions,setShowSessions]=useState(false),[showAdd,setShowAdd]=useState(false),[history,setHistory]=useState<{name:string;logs:Log[]}|null>(null),[reportIndex,setReportIndex]=useState(0);
 async function api(path:string,options?:RequestInit){return readApiResponse(await fetch(path,options));}
 async function refresh(){try{setLinks(await api('/api/links'));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{if(authenticated)void refresh();},[authenticated]);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy('login');setError('');try{await api('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});setLoading(true);setAuthenticated(true);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy('add');setError('');try{await api('/api/links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});await refresh();setShowAdd(false);setNotice('Cuenta agregada. Actualiza sus métricas para obtener la primera lectura.');setView('accounts');}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function action(link:Link,mode:'check'|'history'|'delete'){
  setBusy(link.id);setError('');setNotice('');setReportIndex(0);
  try{if(mode==='history')setHistory({name:link.name,logs:await api(`/api/links/${link.id}`)});
   else{const result=await api(`/api/links/${link.id}${mode==='check'?'/check':''}`,{method:mode==='check'?'POST':'DELETE'});await refresh();if(mode==='check'){if(result.health==='error')setError(result.ai_analysis_result.summary);else setNotice(`Métricas de ${link.name} actualizadas.`);}else setNotice('Cuenta eliminada.');}
  }catch(e){setError((e as Error).message);}finally{setBusy('');}
 }
 async function logout(){try{await api('/api/session',{method:'DELETE'});setAuthenticated(false);setLinks([]);setHistory(null);setShowAdd(false);setShowSessions(false);setError('');}catch(e){setError((e as Error).message);}}
 const filtered=links.filter(link=>(network==='all'||detectPlatform(link.url)===network)&&(!query||`${link.name} ${link.url}`.toLowerCase().includes(query.toLowerCase())));
 const samples:Sample[]=filtered.flatMap(link=>link.link_logs?.[0]?.ai_analysis_result.snapshot?[{snapshot:link.link_logs[0].ai_analysis_result.snapshot,checkedAt:link.link_logs[0].checked_at}]:[]);
 const uniquePosts=new Map<string,{post:SocialSnapshot['posts'][number];platform:Platform;checkedAt:string;account:string}>();
 for(const link of [...filtered].sort((a,b)=>(a.last_checked_at||'').localeCompare(b.last_checked_at||''))){const log=link.link_logs?.[0];if(log?.ai_analysis_result.snapshot)for(const post of log.ai_analysis_result.snapshot.posts)uniquePosts.set(`${log.ai_analysis_result.snapshot.platform}:${post.id}`,{post,platform:log.ai_analysis_result.snapshot.platform,checkedAt:log.checked_at,account:link.name});}
 const posts=[...uniquePosts.values()].map(item=>({...item,...postPerformance(item.post)})).sort((a,b)=>(b.interactions??-1)-(a.interactions??-1));
 const sum=(key:'interactions'|'views')=>{const measured=posts.filter(post=>post[key]!==null);return measured.length?measured.reduce((n,post)=>n+post[key]!,0):null;};
 const interactions=sum('interactions'),totalViews=sum('views');const measuredComments=posts.filter(p=>p.post.metrics.comments!==undefined),comments=measuredComments.length?measuredComments.reduce((n,p)=>n+p.post.metrics.comments,0):null;
 const winner=posts.find(post=>post.interactions!==null),needsAttention=filtered.filter(link=>link.health==='error').length;
 const recommendations=filtered.flatMap(link=>(link.link_logs?.[0]?.ai_analysis_result.recommendations||[]).map(text=>({text,link})));
 const networks=[...new Set(links.map(link=>detectPlatform(link.url)))];
 function csv(){downloadCsv([['Cuenta','URL','Red','Estado','Última lectura','Seguidores'],...filtered.map(link=>[link.name,link.url,platformNames[detectPlatform(link.url)],health[link.health],date(link.last_checked_at),link.link_logs?.[0]?.ai_analysis_result.snapshot?.metrics.followers])],'controlmkt-cuentas.csv');}
 function navigate(next:View){setView(next);setQuery('');}
 function accountTable(){return <section className="surface account-surface"><div className="surface-head"><div><span className="eyebrow">TU ECOSISTEMA</span><h2>Tus cuentas <span className="count-pill">{filtered.length}</span></h2></div><div className="table-tools">{view==='accounts'&&<div className="search-field"><Icon name="search" size={16}/><input aria-label="Buscar cuentas" placeholder="Buscar cuenta…" value={query} onChange={e=>setQuery(e.target.value)}/></div>}<button className="icon-button" aria-label="Refrescar listado" onClick={()=>void refresh()}><Icon name="refresh" size={18}/></button></div></div>
  {loading?<div className="loading-state"><span className="spinner"/> Cargando tus cuentas…</div>:filtered.length?<div className="table-scroll"><table className="account-table"><thead><tr><th>CUENTA</th><th>AUDIENCIA</th><th>PUBLICACIONES</th><th>ÚLTIMA LECTURA</th><th>ESTADO</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{filtered.map(link=>{const platform=detectPlatform(link.url),snapshot=link.link_logs?.[0]?.ai_analysis_result.snapshot;return <tr key={link.id}><td><div className="account-identity"><PlatformBadge platform={platform}/><div><button className="account-name" onClick={()=>void action(link,'history')} disabled={!!busy}>{link.name}</button><a href={link.url} target="_blank" rel="noreferrer">{platformNames[platform]} <Icon name="arrow" size={12}/></a></div></div></td><td><strong>{format(snapshot?.metrics.followers)}</strong><small>seguidores</small></td><td><strong>{snapshot?snapshot.posts.length:'—'}</strong><small>en muestra</small></td><td className="muted small-text">{date(link.last_checked_at)}</td><td><span className={`status-badge status-${link.health}`}><i/>{health[link.health]||link.health}</span></td><td><div className="row-actions"><button className="refresh-button" disabled={!!busy} onClick={()=>void action(link,'check')} aria-label={`Actualizar métricas de ${link.name}`}><Icon name="refresh" size={15}/>{busy===link.id?'Leyendo…':'Actualizar'}</button><button className="icon-button" disabled={!!busy} onClick={()=>void action(link,'history')} aria-label={`Informe de ${link.name}`}><Icon name="chart" size={18}/></button>{view==='accounts'&&<button className="icon-button delete-button" disabled={!!busy} aria-label={`Eliminar ${link.name}`} onClick={()=>{if(confirm(`¿Eliminar ${link.name} y su historial?`))void action(link,'delete');}}><Icon name="trash" size={16}/></button>}</div></td></tr>;})}</tbody></table></div>:<div className="empty-state"><span className="empty-icon"><Icon name="accounts" size={30}/></span><h3>{links.length?'No encontramos cuentas con este filtro':'Tu próxima buena decisión empieza aquí.'}</h3><p>{links.length?'Prueba con otra red o nombre.':'Agrega una cuenta y descubre qué contenido conecta con tu audiencia.'}</p>{!links.length&&<button className="primary" onClick={()=>setShowAdd(true)}><Icon name="plus" size={17}/> Agregar mi primera cuenta</button>}</div>}
 </section>;}
 function ideas(limit?:number){return recommendations.length?<div className="idea-list">{recommendations.slice(0,limit).map((item,index)=><article className="idea-card" key={`${item.link.id}:${index}`}><span className="idea-number">{String(index+1).padStart(2,'0')}</span><div><div className="idea-source"><PlatformBadge platform={detectPlatform(item.link.url)} small/><span>{item.link.name}</span></div><p>{item.text}</p><button className="text-button" onClick={()=>void action(item.link,'history')} disabled={!!busy}>Explorar resultados <Icon name="arrow" size={14}/></button></div></article>)}</div>:<div className="empty-compact"><Icon name="spark" size={26}/><h3>Primero los datos. Después las ideas.</h3><p>Actualiza una cuenta para recibir recomendaciones a partir de su contenido.</p></div>;}
 if(!authenticated)return <div className="login-layout"><aside className="login-story"><Brand/><div><span className="eyebrow">MENOS RUIDO. MÁS CLARIDAD.</span><h1>Detrás de cada<br/>interacción,<br/><em>una oportunidad.</em></h1><p>Encuentra el contenido que conecta.<br/>Dale dirección a tu próxima publicación.</p><div className="login-art" aria-hidden="true"><div className="art-bars">{[32,55,42,72,62,87,100].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><span>Tu siguiente gran idea empieza con datos.</span></div></div><small>ControlMKT · Tu espacio de marketing</small></aside><main className="login-main"><form onSubmit={login}><span className="eyebrow">BIENVENIDO A CONTROLMKT</span><h2>Volvamos a lo que importa.</h2><p className="muted">Ingresa para conocer el rendimiento de tus cuentas.</p><label htmlFor="username">Usuario</label><input id="username" name="username" required autoComplete="username" placeholder="Tu usuario"/><label htmlFor="password">Contraseña</label><input id="password" name="password" type="password" required autoComplete="current-password" placeholder="Tu contraseña"/>{error&&<p role="alert" className="login-error">{error}</p>}<button className="primary" disabled={!!busy}>{busy?'Ingresando…':'Entrar al dashboard'}<Icon name="arrow" size={18}/></button><small className="muted">Acceso inicial: admin / admin</small></form></main></div>;
 return <div className="app-shell"><aside className="sidebar"><Brand/><div className="workspace-chip"><span className="workspace-avatar">M</span><div>Mi espacio de marketing<small>Administrador</small></div></div><span className="nav-label">WORKSPACE</span><nav aria-label="Navegación principal">{([['overview','grid','Resumen'],['content','chart','Contenido'],['accounts','accounts','Cuentas'],['ideas','spark','Recomendaciones']] as const).map(([key,icon,label])=><button key={key} className={`nav-item ${view===key?'active':''}`} aria-current={view===key?'page':undefined} onClick={()=>navigate(key)}><Icon name={icon}/>{label}{key==='accounts'&&<span>{links.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="connect-card"><span className="connect-symbol"><Icon name="connect" size={22}/></span><h3>Tu sesión, conectada.</h3><p>Importa tus sesiones para leer más de tus redes.</p><button onClick={()=>setShowSessions(true)}>Conectar redes <Icon name="arrow" size={15}/></button></div><button className="logout-button" onClick={()=>void logout()}><Icon name="out" size={18}/> Cerrar sesión</button><small>Datos que inspiran decisiones.</small></div></aside>
 <div className="app-main"><header className="topbar"><div className="breadcrumb"><span>Workspace</span><span>/</span><strong>{view==='overview'?'Resumen':view==='content'?'Contenido':view==='accounts'?'Cuentas':'Recomendaciones'}</strong></div><div className="topbar-right"><span className="live-label"><i/> Últimas lecturas</span><button className="mobile-logout icon-button" aria-label="Cerrar sesión" onClick={()=>void logout()}><Icon name="out" size={18}/></button><button className="admin-avatar" onClick={()=>setShowSessions(true)} aria-label="Gestionar sesiones">A</button></div></header><main className="dashboard-main">
 <div className="page-heading"><div><span className="eyebrow">TU MARKETING, CON PERSPECTIVA</span><h1>{views[view].title}</h1><p>{views[view].subtitle}</p></div><div className="heading-actions"><button className="secondary" onClick={csv}><Icon name="download" size={17}/> Exportar</button><button className="primary" onClick={()=>setShowAdd(true)}><Icon name="plus" size={18}/> Agregar cuenta</button></div></div>
 <div className="filter-bar"><div className="network-filters" aria-label="Filtrar por red"><button className={network==='all'?'selected':''} onClick={()=>setNetwork('all')}>Todas las redes</button>{networks.map(platform=><button key={platform} className={network===platform?'selected':''} onClick={()=>setNetwork(platform)}><PlatformBadge platform={platform} small/>{platformNames[platform]}</button>)}</div><span className="sample-label"><Icon name="info" size={14}/> Muestra de publicaciones visibles</span></div>
 {error&&<div role="alert" className="feedback error"><Icon name="info" size={19}/><span>{error}</span><button className="icon-button" aria-label="Cerrar error" onClick={()=>setError('')}><Icon name="close" size={16}/></button></div>}{notice&&<div role="status" className="feedback success"><Icon name="check" size={19}/><span>{notice}</span><button className="icon-button" aria-label="Cerrar aviso" onClick={()=>setNotice('')}><Icon name="close" size={16}/></button></div>}
 {view==='overview'&&<><div className="metric-grid">{[{label:'Interacciones',value:interactions,icon:'heart',detail:'Likes, comentarios y compartidos',accent:'green'},{label:'Visualizaciones',value:totalViews,icon:'eye',detail:'Vistas observadas en la muestra',accent:'blue'},{label:'Comentarios',value:comments,icon:'message',detail:'Conversaciones en tus publicaciones',accent:'purple'},{label:'Contenido medido',value:posts.length||null,icon:'play',detail:`${filtered.length} cuentas y enlaces monitoreados`,accent:'orange'}].map(metric=><article className={`metric-card ${metric.accent}`} key={metric.label}><div className="metric-top"><span>{metric.label}</span><span className="metric-icon"><Icon name={metric.icon} size={19}/></span></div><strong>{loading?'…':format(metric.value)}</strong><p>{metric.detail}</p><div className="metric-footer"><span className="tiny-dot"/> {metric.value===null?'Actualiza una cuenta para empezar':'Última lectura disponible'}</div></article>)}</div>
 <div className="overview-grid"><section className="surface distribution"><div className="surface-head"><div><span className="eyebrow">DÓNDE CONECTAS MÁS</span><h2>Interacciones por red</h2></div><span className="subtle-pill">Última muestra</span></div><div className="distribution-body">{samples.length?networks.filter(platform=>network==='all'||network===platform).map(platform=>{const rows=posts.filter(p=>p.platform===platform&&p.interactions!==null),value=rows.length?rows.reduce((n,p)=>n+p.interactions!,0):null;const fraction=value===null?0:interactions?value/interactions*100:0;return <div className="distribution-row" key={platform}><div><PlatformBadge platform={platform} small/><span>{platformNames[platform]}</span><strong>{format(value)}</strong></div><div className="bar-track"><span className={`bar-${platform}`} style={{width:`${fraction}%`}}/></div></div>;}):<div className="chart-empty"><Icon name="chart" size={36}/><p>Tu panorama aparecerá con la primera lectura.</p></div>}</div><p className="chart-footnote">Una publicación se cuenta una vez. Los datos ausentes no equivalen a cero.</p></section>
 <section className="spotlight"><div className="spotlight-label"><Icon name="spark" size={16}/> CONTENIDO DESTACADO</div>{winner?<><div className="spotlight-account"><PlatformBadge platform={winner.platform} small/><span>{winner.account}</span><span className="format-pill">{winner.post.kind==='video'?'Video':'Publicación'}</span></div><h2>{winner.post.text||'Tu publicación con más interacciones'}</h2><div className="spotlight-numbers"><div><strong>{format(winner.interactions)}{winner.partial?'*':''}</strong><span>interacciones</span></div><div><strong>{format(winner.views)}</strong><span>visualizaciones</span></div></div><a className="spotlight-link" href={winner.post.url} target="_blank" rel="noreferrer">Ver publicación <Icon name="arrow" size={17}/></a></>:<><h2>Tu próximo contenido destacado está por descubrirse.</h2><p>Actualiza las métricas de tus cuentas para encontrarlo.</p><button className="spotlight-link" onClick={()=>navigate('accounts')}>Explorar cuentas <Icon name="arrow" size={17}/></button></>}<span className="spotlight-orbit" aria-hidden="true"/></section></div>
 {accountTable()}<section className="surface ideas-surface"><div className="surface-head"><div><span className="eyebrow">EL SIGUIENTE PASO</span><h2>Ideas para tu contenido</h2></div><button className="text-button" onClick={()=>navigate('ideas')}>Ver recomendaciones <Icon name="arrow" size={16}/></button></div>{ideas(2)}</section></>}
 {view==='content'&&<>{samples.length?<PerformanceOverview samples={samples}/>:<section className="surface empty-state"><Icon name="chart" size={32}/><h3>Aún no hay contenido para comparar.</h3><p>Actualiza las métricas de una cuenta para comenzar.</p><button className="primary" onClick={()=>navigate('accounts')}>Ir a mis cuentas <Icon name="arrow" size={16}/></button></section>}</>}
 {view==='accounts'&&<>{needsAttention>0&&<div className="attention-banner"><Icon name="info" size={19}/><span>{needsAttention} {needsAttention===1?'cuenta requiere':'cuentas requieren'} atención. Abre su informe para conocer el motivo.</span><button className="text-button" onClick={()=>setShowSessions(true)}>Revisar sesiones <Icon name="arrow" size={15}/></button></div>}{accountTable()}</>}
 {view==='ideas'&&<section className="surface ideas-surface"><div className="surface-head"><div><span className="eyebrow">DE LA LECTURA A LA ACCIÓN</span><h2>Recomendaciones para tus cuentas</h2><p>Generadas con reglas locales a partir de las métricas disponibles.</p></div><span className="idea-emblem"><Icon name="spark" size={22}/></span></div>{ideas()}</section>}
 <footer className="dashboard-footer"><span>controlmkt<span className="brand-dot">.</span></span><p>Las métricas observadas representan una muestra, no el alcance total de una cuenta.</p></footer>
 </main></div>
 {showAdd&&<Modal title="Agregar cuenta" onClose={()=>setShowAdd(false)}><div className="modal-header"><div><span className="eyebrow">AMPLÍA TU PERSPECTIVA</span><h2>Agrega una cuenta.</h2><p className="muted">Un perfil, una publicación o una página web.</p></div><button className="icon-button" aria-label="Cerrar formulario" onClick={()=>setShowAdd(false)}><Icon name="close"/></button></div><form className="add-form" onSubmit={add}><label htmlFor="account-name">¿Cómo quieres llamarla?</label><input id="account-name" name="name" placeholder="Mi marca · TikTok" required maxLength={120}/><label htmlFor="account-url">Enlace del perfil o publicación</label><input id="account-url" name="url" type="url" placeholder="https://www.tiktok.com/@marca" required/><div className="form-grid"><div><label htmlFor="check-method">Método de lectura</label><select id="check-method" name="check_method"><option value="auto">Detectar automáticamente</option><option value="browser">Navegador / JavaScript</option></select></div><div><label htmlFor="check-frequency">Frecuencia preferida</label><select id="check-frequency" name="check_frequency"><option value="manual">Manual</option><option value="hourly">Cada hora</option><option value="daily">Diaria</option></select></div></div><p className="form-note"><Icon name="info" size={16}/> Por ahora las actualizaciones son manuales. Guardaremos tu frecuencia preferida.</p>{error&&<p role="alert" className="login-error">{error}</p>}<button className="primary" disabled={!!busy}>{busy==='add'?'Agregando…':'Agregar cuenta'}<Icon name="arrow" size={17}/></button></form></Modal>}
 {showSessions&&<Modal title="Conectar redes" onClose={()=>setShowSessions(false)}><SessionManager onClose={()=>setShowSessions(false)}/></Modal>}
 {history&&<Modal title={`Resultados de ${history.name}`} onClose={()=>setHistory(null)} drawer><div className="modal-header"><div><span className="eyebrow">TU CUENTA, EN DETALLE</span><h2>Resultados · {history.name}</h2></div><button className="icon-button" aria-label="Cerrar informe" onClick={()=>setHistory(null)}><Icon name="close"/></button></div>{!history.logs.length?<div className="empty-compact"><Icon name="chart" size={30}/><h3>El primer informe está por llegar.</h3><p>Actualiza las métricas de esta cuenta.</p></div>:<><label htmlFor="report-date">Lectura del informe</label><select id="report-date" value={reportIndex} onChange={e=>setReportIndex(Number(e.target.value))}>{history.logs.map((log,index)=><option key={log.id} value={index}>{index===0?'Última lectura · ':''}{date(log.checked_at)}</option>)}</select>{history.logs.slice(reportIndex,reportIndex+1).map(log=>{const analysis=log.ai_analysis_result,previous=history.logs.slice(reportIndex+1).find(item=>item.ai_analysis_result.snapshot);return <div key={log.id} className="report-content"><p className="report-summary">{analysis.summary}</p>{analysis.snapshot&&<><div className="report-metrics">{[['Seguidores',analysis.snapshot.metrics.followers],['Publicaciones',analysis.snapshot.posts.length]].map(([label,value])=><div key={label}><span>{label}</span><strong>{format(value as number|undefined)}</strong></div>)}</div><PerformancePanel snapshot={analysis.snapshot} previous={previous?.ai_analysis_result.snapshot} checkedAt={log.checked_at} previousAt={previous?.checked_at} history={history.logs.filter(item=>item.ai_analysis_result.snapshot).map(item=>({snapshot:item.ai_analysis_result.snapshot!,checkedAt:item.checked_at}))}/></>}{!!analysis.recommendations?.length&&<div className="report-ideas"><h3><Icon name="spark" size={18}/> Próximos pasos</h3><ul>{analysis.recommendations.map(rec=><li key={rec}>{rec}</li>)}</ul></div>}<details className="technical-details"><summary>Detalles de la lectura</summary><p>Respuesta HTTP: {log.http_status||'sin respuesta'}</p>{analysis.snapshot?.notes.map(note=><p key={note}>{note}</p>)}</details></div>;})}</>}</Modal>}
 </div>;
}
