'use client';
import { useState } from 'react';
import { rankPosts,postPerformance,type RankingMode } from '@/lib/performance';
import type { SocialSnapshot } from '@/lib/social';
import { platformNames } from '@/lib/platform';

export type Sample={snapshot:SocialSnapshot;checkedAt:string};
const n=(value:number|null)=>value===null?'No disponible':value.toLocaleString('es-PY',{maximumFractionDigits:2});
const kind=(value?:string)=>value==='video'?'Video':value==='post'?'Post':'Sin clasificar';
export function downloadCsv(rows:unknown[][],filename:string){
 const csv=rows.map(row=>row.map(value=>'"'+String(value??'No disponible').replace(/^[=+@\-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');
 const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);
}
export default function PerformancePanel({snapshot,previous,checkedAt,previousAt,history=[]}:{snapshot:SocialSnapshot;previous?:SocialSnapshot;checkedAt?:string;previousAt?:string;history?:Sample[]}){
 const [mode,setMode]=useState<RankingMode>('interactions'),[filter,setFilter]=useState('all'),[selected,setSelected]=useState(''),[expanded,setExpanded]=useState(false);
 const rows=rankPosts(snapshot,mode,previous,filter);const scored=rows.filter(row=>row.interactions!==null);const observed=scored.reduce((sum,row)=>sum+row.interactions!,0);const winner=rows.find(row=>(mode==='interactions'?row.interactions:mode==='views'?row.views:mode==='rate'?row.rate:row.growth)!==null);
 const exportReport=()=>downloadCsv([['Red','Fecha control','Tipo','Publicación','URL','Interacciones observadas','Suma parcial','Likes','Reacciones','Comentarios','Compartidos','Vistas','Tasa por vista (%)','Variación interacciones'],...rows.map(row=>[platformNames[snapshot.platform],checkedAt||'',kind(row.post.kind),row.post.text,row.post.url,row.interactions,row.partial?'Sí':'No',row.post.metrics.likes,row.post.metrics.reactions,row.post.metrics.comments,row.post.metrics.shares,row.views,row.rate,row.growth])],'repercusion-publicaciones.csv');
 const timeline=history.filter(sample=>sample.snapshot.platform===snapshot.platform).map(sample=>{const post=sample.snapshot.posts.find(post=>post.id===selected);return {date:sample.checkedAt,row:post?postPerformance(post):null};}).sort((a,b)=>a.date.localeCompare(b.date));
 return <section className="performance-panel border border-gray-200 rounded-xl p-4 space-y-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Repercusión de publicaciones · {platformNames[snapshot.platform]}</h3><button onClick={exportReport}>↓ Exportar ranking</button></div>
  <div className="grid sm:grid-cols-2 gap-3"><div><label>Ordenar por</label><select aria-label="Ordenar ranking" value={mode} onChange={e=>setMode(e.target.value as RankingMode)}><option value="interactions">Más interacciones</option><option value="views">Más vistas</option><option value="rate">Mayor tasa de interacción por vista</option><option value="growth">Mayor crecimiento entre controles</option></select></div><div><label>Formato</label><select aria-label="Filtrar formato" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option><option value="video">Videos</option><option value="post">Posts</option><option value="unknown">Sin clasificar</option></select></div></div>
  <div className="grid sm:grid-cols-3 gap-3 text-sm"><div className="bg-gray-50 rounded-lg p-3"><p className="text-gray-500">Contenido en muestra</p><strong className="text-xl">{rows.length}</strong></div><div className="bg-gray-50 rounded-lg p-3"><p className="text-gray-500">Interacciones observadas</p><strong className="text-xl">{scored.length?n(observed):'No disponibles'}</strong><p className="text-xs text-gray-500">Suma de esta muestra, no de toda la cuenta.</p></div><div className="bg-emerald-50 rounded-lg p-3"><p className="text-emerald-700">Primero según el criterio elegido</p>{winner?<a className="font-semibold text-emerald-900" href={winner.post.url} target="_blank" rel="noreferrer">{winner.post.text.slice(0,90)||winner.post.id}</a>:<p>Sin datos comparables</p>}</div></div>
  <details className="text-xs text-gray-500"><summary className="cursor-pointer">Cómo se calculan las métricas</summary><p className="mt-2">Interacciones = likes o reacciones + comentarios + compartidos. Reacciones reemplaza likes para evitar duplicados. Un asterisco indica suma parcial. Tasa = interacciones observadas / vistas × 100; las vistas no equivalen a personas únicas.</p></details>
  {previousAt&&checkedAt&&<p className="text-xs text-gray-500">Variación desde {new Date(previousAt).toLocaleString('es-PY')} hasta {new Date(checkedAt).toLocaleString('es-PY')}. Solo se comparan la misma publicación y los mismos contadores disponibles.</p>}
  {mode==='growth'&&!previous&&<p className="text-xs text-amber-700">Para medir crecimiento necesitas dos controles del mismo enlace. Abre su Informe después de volver a ejecutar el control.</p>}
  <button onClick={()=>setExpanded(!expanded)}>{expanded?'Vista resumida':'Ver todas las métricas'}</button><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr><th># / TIPO</th><th>PUBLICACIÓN</th><th>INTERACCIONES</th>{expanded&&<th>LIKES / REACCIONES</th>}<th>COMENTARIOS</th>{expanded&&<th>COMPARTIDOS</th>}<th>VISTAS</th>{(expanded||mode==='rate')&&<th>TASA POR VISTA</th>}{(expanded||mode==='growth')&&<th>VARIACIÓN</th>}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.post.id}><td className="whitespace-nowrap">{index+1} · {kind(row.post.kind)}</td><td className="min-w-48 max-w-sm"><a href={row.post.url} target="_blank" rel="noreferrer" className="text-emerald-700">{row.post.text.slice(0,180)||row.post.id}</a>{history.length>1&&<button className="mt-2" onClick={()=>setSelected(selected===row.post.id?'':row.post.id)}>Ver evolución</button>}</td><td className="font-semibold">{n(row.interactions)}{row.interactions!==null&&row.partial?' *':''}</td>{expanded&&<td>{n(row.post.metrics.reactions??row.post.metrics.likes??null)}</td>}<td>{n(row.post.metrics.comments??null)}</td>{expanded&&<td>{n(row.post.metrics.shares??null)}</td>}<td>{n(row.views)}</td>{(expanded||mode==='rate')&&<td>{row.rate===null?'No disponible':`${n(row.rate)}%${row.partial?' *':''}`}</td>}{(expanded||mode==='growth')&&<td>{row.growth===null?'Sin referencia':`${row.growth>0?'+':''}${n(row.growth)}${row.partial?' *':''}`}</td>}</tr>)}</tbody></table>{!rows.length&&<p className="py-5 text-sm text-gray-500">No hay publicaciones de este formato con datos en la muestra.</p>}</div>
  {selected&&<div className="overflow-x-auto"><h4 className="font-semibold text-sm">Evolución de {selected}</h4><table className="w-full text-xs"><thead><tr><th>CONTROL</th><th>INTERACCIONES</th><th>VISTAS</th><th>TASA POR VISTA</th></tr></thead><tbody>{timeline.map(point=><tr key={point.date}><td>{new Date(point.date).toLocaleString('es-PY')}</td><td>{point.row?n(point.row.interactions)+(point.row.partial?' *':''):'Fuera de muestra'}</td><td>{n(point.row?.views??null)}</td><td>{point.row?.rate===null||!point.row?'No disponible':`${n(point.row.rate)}%`}</td></tr>)}</tbody></table></div>}
 </section>;
}

export function PerformanceOverview({samples}:{samples:Sample[]}){
 const [selected,setSelected]=useState('');const platforms=[...new Set(samples.map(sample=>sample.snapshot.platform))];const platform=platforms.includes(selected as SocialSnapshot['platform'])?selected:platforms[0];if(!platform)return null;
 const matching=samples.filter(sample=>sample.snapshot.platform===platform).sort((a,b)=>a.checkedAt.localeCompare(b.checkedAt));const posts=new Map<string,SocialSnapshot['posts'][number]>();for(const sample of matching)for(const post of sample.snapshot.posts)posts.set(post.id,post);
 const snapshot:SocialSnapshot={version:1,platform:platform as SocialSnapshot['platform'],metrics:{},posts:[...posts.values()],coverage:'partial',notes:[]};
 return <section className="performance-overview bg-white rounded-xl border border-gray-200 p-6 mb-8 space-y-4"><div className="flex flex-wrap gap-4 items-center justify-between"><div><h2 className="font-semibold">Qué contenido genera mayor repercusión</h2><p className="text-xs text-gray-500 mt-1">Última lectura disponible de cada enlace. Una publicación repetida se cuenta una vez; se conserva su lectura más reciente.</p></div><select className="max-w-48" aria-label="Red del ranking" value={platform} onChange={e=>setSelected(e.target.value)}>{platforms.map(p=><option key={p} value={p}>{platformNames[p]}</option>)}</select></div><PerformancePanel key={platform} snapshot={snapshot}/></section>;
}
